#!/bin/bash
echo "(+)--- Backing up to run make"
cd ..
make
echo "(+)--- The error is expected. Compiling manually..."
cd src
echo "(+)--- Compiling our files"
g++ -c pairwise/hmmsum.cpp;
echo "(+)--- Now linking and generating executable xclustsum"
g++  -g -O2   -o xclustsum FullPairwiseAlign.o FastPairwiseAlign.o MSFFileParser.o FileReader.o PIRFileParser.o RSFFileParser.o GDEFileParser.o InFileStream.o ClustalFileParser.o PearsonFileParser.o FileParser.o EMBLFileParser.o RootedClusterTree.o UPGMAAlgorithm.o Node.o RootedGuideTree.o RootedTreeOutput.o Tree.o ClusterTree.o TreeInterface.o UnRootedClusterTree.o ClusterTreeOutput.o RandomGenerator.o NJTree.o AlignmentSteps.o InteractiveMenu.o CommandLineParser.o SubMatrix.o Iteration.o MSA.o MyersMillerProfileAlign.o ProfileStandard.o ProfileWithSub.o ProfileBase.o LowScoreSegProfile.o OutputFile.o UserParameters.o Utility.o InvalidCombination.o DebugLog.o ClustalWResources.o VectorOutOfRange.o SymMatrix.o Stats.o Help.o Alignment.o AlignmentOutput.o ObjectiveScore.o Sequence.o Clustal.o main.o hmmsum.o database.o seq2gca.o hmmstr.o -lgfortran

cp xclustsum ~/HMMSUM/CLUSTSUM_RV11/xclustsum
cp xclustsum ~/HMMSUM/CLUSTSUM_RV12/xclustsum
